# Generated by Django 4.1.6 on 2023-02-11 16:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('modified', models.DateTimeField(verbose_name='Last modified')),
                ('text', models.CharField(max_length=280, verbose_name='Tweet')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tweets', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('in_reply_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='tweets.tweet', verbose_name='Replies')),
                ('in_retweet_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='retweets', to='tweets.tweet', verbose_name='Retweets')),
                ('likes', models.ManyToManyField(related_name='all_likes', to=settings.AUTH_USER_MODEL, verbose_name='Likes')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
