# Generated by Django 4.1.6 on 2023-02-28 21:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='notification_box', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=280, verbose_name='Notification message')),
                ('link', models.URLField(verbose_name='Redirect link')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('clicked', models.BooleanField(verbose_name='Notifcation has been clicked')),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='notifications.notificationbox', verbose_name='Notification Box')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
